const strains=[
{id:'gelato41',name:'Gelato 41',type:'Hybrid',thc:'22–28%',terpenes:['Caryophyllene','Limonene','Linalool'],effects:['Relaxed','Happy','Creative'],flavor:'Creamy citrus, pepper',desc:'Dessert-forward hybrid with a balanced reputation.',rating:4.7,accent:'#a987ff'},
{id:'blue-dream',name:'Blue Dream',type:'Sativa',thc:'18–24%',terpenes:['Myrcene','Pinene','Caryophyllene'],effects:['Happy','Creative','Focused'],flavor:'Berry, pine',desc:'Classic berry-forward cultivar often described as bright and easygoing.',rating:4.5,accent:'#72a6ff'},
{id:'gmo',name:'GMO',type:'Indica',thc:'24–31%',terpenes:['Caryophyllene','Myrcene','Limonene'],effects:['Relaxed','Sleepy'],flavor:'Savory, diesel, spice',desc:'Heavy, pungent profile with unmistakable savory notes.',rating:4.8,accent:'#b2ff70'},
{id:'jack-herer',name:'Jack Herer',type:'Sativa',thc:'18–23%',terpenes:['Terpinolene','Caryophyllene','Pinene'],effects:['Focused','Creative','Happy'],flavor:'Pine, spice, citrus',desc:'A bright aromatic profile associated with clear, energetic character.',rating:4.6,accent:'#ffcf65'},
{id:'wedding-cake',name:'Wedding Cake',type:'Hybrid',thc:'22–27%',terpenes:['Caryophyllene','Limonene','Myrcene'],effects:['Relaxed','Happy'],flavor:'Vanilla, pepper, earth',desc:'Dense dessert-style profile with sweet spice and earth.',rating:4.7,accent:'#ff99cf'},
{id:'northern-lights',name:'Northern Lights',type:'Indica',thc:'16–21%',terpenes:['Myrcene','Caryophyllene','Pinene'],effects:['Relaxed','Sleepy'],flavor:'Earth, pine, sweet',desc:'Old-school indica profile known for earthy pine and a mellow reputation.',rating:4.6,accent:'#68ffad'}
];
const demoNews=[
{source:'PREROLL.ORG GUIDE',title:'How to judge a pre-roll beyond THC percentage',text:'Burn consistency, flower quality, aroma, draw, freshness and construction can matter as much as one potency number.'},
{source:'TERPENE 101',title:'Limonene: citrus aroma, chemistry and what the label really tells you',text:'A terpene label describes chemistry and aroma potential; it does not guarantee a specific experience for every person.'},
{source:'COMMUNITY',title:'What should a useful pre-roll review include?',text:'A repeatable review format makes comparisons better: aroma, draw, burn, ash, flavor, freshness, effects and value.'}
];
const store={get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set(k,v){localStorage.setItem(k,JSON.stringify(v))}};
let currentUser=store.get('pr_user',null), posts=store.get('pr_posts',[
{id:1,title:'What makes a pre-roll actually premium?',category:'General',body:'Flower quality first, but construction and freshness make a huge difference too. What do you score?',author:'Jay',likes:14,created:Date.now()-8200000},
{id:2,title:'Best burn test: white ash or overhyped?',category:'Pre-Roll Reviews',body:'Curious what everyone actually uses to judge a clean, even burn.',author:'Mia',likes:9,created:Date.now()-4400000},
{id:3,title:'NY community check-in',category:'New York',body:'What are people reviewing lately? Keep it about legal products and actual experiences.',author:'NorthShore',likes:6,created:Date.now()-1900000}
]), reviews=store.get('pr_reviews',[]), saved=store.get('pr_saved',[]);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
function renderStrains(query=''){const type=$('#typeFilter').value,effect=$('#effectFilter').value,q=query.toLowerCase();const list=strains.filter(s=>(type==='all'||s.type===type)&&(effect==='all'||s.effects.includes(effect))&&(!q||JSON.stringify(s).toLowerCase().includes(q)));$('#strainGrid').innerHTML=list.map(s=>`<article class="strain-card" style="--accent:${s.accent}"><div class="strain-meta"><span class="pill">${s.type}</span><span class="pill">THC ${s.thc}</span></div><h3>${s.name}</h3><div class="rating">★★★★★ <span class="muted">${s.rating}</span></div><p>${s.desc}</p><div class="strain-meta">${s.effects.map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="card-actions"><button class="btn ghost small" onclick="openStrain('${s.id}')">Details & reviews</button><button class="btn small" onclick="toggleSave('${s.id}')">${saved.includes(s.id)?'★ Saved':'☆ Save'}</button></div></article>`).join('')||'<p class="muted">No matches. Try another filter.</p>';$('#strainCount').textContent=strains.length}
window.toggleSave=id=>{saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];store.set('pr_saved',saved);renderStrains($('#globalSearch').value);renderSaved();toast(saved.includes(id)?'Saved to your stash':'Removed from stash')}
function renderSaved(){const el=$('#savedList');el.innerHTML=saved.length?saved.map(id=>{const s=strains.find(x=>x.id===id);return s?`<div class="saved-item"><button class="text-btn" onclick="openStrain('${s.id}')">${s.name}</button><button class="text-btn" onclick="toggleSave('${s.id}')">×</button></div>`:''}).join(''):'<span class="muted">Nothing saved yet.</span>'}
window.openStrain=async id=>{const s=strains.find(x=>x.id===id);if(window.PREROLL_CONFIG.API_URL){try{const r=await fetch(window.PREROLL_CONFIG.API_URL+'/api/reviews');if(r.ok)reviews=await r.json()}catch{}}const rs=reviews.filter(r=>r.strain===id);showModal(`<p class="eyebrow">${s.type} • THC ${s.thc}</p><h2 style="font-size:2.7rem">${s.name}</h2><p>${s.desc}</p><p><strong>Flavor:</strong> ${s.flavor}</p><p><strong>Terpenes:</strong> ${s.terpenes.join(', ')}</p><p><strong>Commonly reported:</strong> ${s.effects.join(', ')}</p><h3>Community reviews</h3><div class="review-list">${rs.length?rs.map(r=>`<div class="review"><strong>${esc(r.author)}</strong> • ${r.overall}/5<p>${esc(r.text)}</p><small class="muted">Burn ${r.burn}/5 · Flavor ${r.flavor}/5 · Value ${r.value}/5</small></div>`).join(''):'<p class="muted">No reviews yet.</p>'}</div><hr style="border-color:#273029"><form id="reviewForm" class="form-stack"><h3>Add a review</h3><div class="score-row"><label>Overall<input name="overall" type="number" min="1" max="5" value="5"></label><label>Burn<input name="burn" type="number" min="1" max="5" value="5"></label><label>Flavor<input name="flavor" type="number" min="1" max="5" value="5"></label><label>Value<input name="value" type="number" min="1" max="5" value="4"></label></div><textarea name="text" maxlength="600" placeholder="What stood out?" required></textarea><button class="btn primary">Publish review</button></form>`);$('#reviewForm').onsubmit=async e=>{e.preventDefault();if(!currentUser)return showAuth('Create an account or log in before reviewing.');const f=new FormData(e.target);const payload={strain:id,text:f.get('text'),overall:+f.get('overall'),burn:+f.get('burn'),flavor:+f.get('flavor'),value:+f.get('value')};if(window.PREROLL_CONFIG.API_URL){try{const r=await fetch(window.PREROLL_CONFIG.API_URL+'/api/reviews',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+localStorage.getItem('pr_token')},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not publish');reviews.unshift(data)}catch(err){return toast(err.message)}}else{reviews.unshift({...payload,author:currentUser.username,created:Date.now()});store.set('pr_reviews',reviews)}updateStats();openStrain(id);toast('Review published')}}
async function renderPosts(){if(window.PREROLL_CONFIG.API_URL){try{const r=await fetch(window.PREROLL_CONFIG.API_URL+'/api/posts');if(r.ok){posts=await r.json()}}catch{}}posts.sort((a,b)=>b.created-a.created);$('#forumFeed').innerHTML=posts.map(p=>`<article class="post"><div class="forum-meta"><span class="pill">${esc(p.category)}</span><span class="pill">@${esc(p.author)}</span></div><h4>${esc(p.title)}</h4><p>${esc(p.body)}</p><div class="post-actions"><button onclick="likePost(${p.id})">▲ ${p.likes||0}</button><span>${new Date(p.created).toLocaleString()}</span></div></article>`).join('');$('#postCount').textContent=posts.length}
window.likePost=async id=>{if(window.PREROLL_CONFIG.API_URL){try{await fetch(window.PREROLL_CONFIG.API_URL+'/api/posts/'+id+'/like',{method:'POST'});return renderPosts()}catch{return toast('Could not reach server')}}const p=posts.find(x=>x.id===id);if(p){p.likes=(p.likes||0)+1;store.set('pr_posts',posts);renderPosts()}}
function renderNews(){$('#newsGrid').innerHTML=demoNews.map(n=>`<article class="news-card"><span class="source">${n.source}</span><h3>${n.title}</h3><p>${n.text}</p></article>`).join('')}
function updateStats(){$('#reviewCount').textContent=reviews.length;$('#postCount').textContent=posts.length;$('#strainCount').textContent=strains.length}
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
async function apiRequest(path,options={}){const base=(window.PREROLL_CONFIG.API_URL||'').replace(/\\/$/,'');const res=await fetch(base+path,{...options,credentials:'include',headers:{'Content-Type':'application/json',...(options.headers||{})}});let data={};try{data=await res.json()}catch{}if(!res.ok)throw new Error(data.error||'Request failed');return data}
async function showAuth(message=''){showModal('<p class="eyebrow">MEMBER ACCESS</p><h2 style="font-size:2.6rem">Join Preroll.org</h2>'+(message?'<p class="muted">'+esc(message)+'</p>':'')+'<div class="auth-tabs"><button id="signupTab" class="btn primary small">Sign up</button><button id="loginTab" class="btn ghost small">Log in</button></div><form id="authForm" class="form-stack"><input name="username" minlength="3" maxlength="24" pattern="[A-Za-z0-9_]{3,24}" placeholder="Username" required autocomplete="username"><input name="email" type="email" maxlength="254" placeholder="Email" required autocomplete="email"><input name="password" type="password" minlength="12" maxlength="128" placeholder="Password (12+ characters)" required autocomplete="new-password"><button class="btn primary">Create account</button><small>Your password is securely hashed on the server and never stored in your browser.</small></form>');let mode='signup',form=$('#authForm'),submit=form.querySelector('button'),name=form.querySelector('[name=username]');const render=()=>{submit.textContent=mode==='signup'?'Create account':'Log in';name.style.display=mode==='signup'?'':'none';name.required=mode==='signup';form.querySelector('[name=password]').autocomplete=mode==='signup'?'new-password':'current-password'};$('#signupTab').onclick=()=>{mode='signup';render()};$('#loginTab').onclick=()=>{mode='login';render()};form.onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{const f=new FormData(form),data=await apiRequest('/api/'+mode,{method:'POST',body:JSON.stringify({username:String(f.get('username')||''),email:String(f.get('email')||''),password:String(f.get('password')||'')})});currentUser=data.user;store.set('pr_user',currentUser);localStorage.removeItem('pr_token');syncAuth();$('#modal').classList.add('hidden');toast('Welcome, '+currentUser.username)}catch(err){toast(err.message)}finally{submit.disabled=false}}}
function syncAuth(){if(currentUser){$('#loginBtn').classList.add('hidden');$('#profileBtn').classList.remove('hidden');$('#profileBtn').textContent='@'+currentUser.username}else{$('#loginBtn').classList.remove('hidden');$('#profileBtn').classList.add('hidden')}}
function showProfile(){showModal(`<p class="eyebrow">PROFILE</p><h2 style="font-size:2.7rem">@${esc(currentUser.username)}</h2><div class="profile-grid"><p><strong>Email:</strong> ${esc(currentUser.email)}</p><p><strong>Saved strains:</strong> ${saved.length}</p><p><strong>Reviews:</strong> ${reviews.filter(r=>r.author===currentUser.username).length}</p><p><strong>Discussions:</strong> ${posts.filter(p=>p.author===currentUser.username).length}</p><button id="logout" class="btn ghost">Log out</button></div>`); $('#logout').onclick=async()=>{try{await apiRequest('/api/logout',{method:'POST'})}catch{}currentUser=null;localStorage.removeItem('pr_user');localStorage.removeItem('pr_token');syncAuth();$('#modal').classList.add('hidden');toast('Logged out')}}
function aiAnswer(q){const x=q.toLowerCase();if(x.includes('limonene'))return 'Limonene is a terpene with a citrus-like aroma found in cannabis and many other plants. A terpene label describes chemistry and aroma; it does not guarantee a specific effect.';if(x.includes('quality')||x.includes('well-made')||x.includes('pre-roll'))return 'For a pre-roll review, check freshness, aroma, draw resistance, evenness of the burn, whether it can stay lit without constant correction, flavor through the session, flower quality, and value. Ash color alone is not a reliable quality test.';const matches=strains.filter(s=>s.effects.some(e=>x.includes(e.toLowerCase()))||x.includes(s.type.toLowerCase())||x.includes(s.name.toLowerCase()));if(matches.length)return `From this site's demo catalog, take a look at ${matches.slice(0,3).map(s=>s.name).join(', ')}. Their catalog tags match parts of your question. Treat those tags as community descriptors, not medical predictions.`;if(x.includes('terpene'))return 'Terpenes are aromatic compounds found across plants. In cannabis, common examples include myrcene, limonene, pinene and caryophyllene. They help describe aroma and chemistry, but individual effects are not guaranteed.';return 'I can search the local catalog by strain name, type, effects such as relaxed/focused/creative, or explain common terpenes. Try asking “Which catalog strains are focused?”'}
$('#ageYes').onclick=()=>{localStorage.setItem('pr_age','yes');$('#ageGate').classList.add('hidden')};$('#ageNo').onclick=()=>{$('#ageMessage').textContent='Sorry — this site is for adults 21+.'};if(localStorage.getItem('pr_age')==='yes')$('#ageGate').classList.add('hidden');
$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));$('#loginBtn').onclick=()=>showAuth();$('#ctaJoin').onclick=()=>showAuth();$('#profileBtn').onclick=showProfile;$('#modalClose').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target.id==='modal')$('#modal').classList.add('hidden')};
$('#heroSearch').onsubmit=e=>{e.preventDefault();renderStrains($('#globalSearch').value);location.hash='discover'};$('#typeFilter').onchange=()=>renderStrains($('#globalSearch').value);$('#effectFilter').onchange=()=>renderStrains($('#globalSearch').value);
$('#postForm').onsubmit=async e=>{e.preventDefault();if(!currentUser)return showAuth('Log in before posting to the forum.');const p={id:Date.now(),title:$('#postTitle').value.trim(),category:$('#postCategory').value,body:$('#postBody').value.trim(),author:currentUser.username,likes:0,created:Date.now()};if(window.PREROLL_CONFIG.API_URL){try{const r=await fetch(window.PREROLL_CONFIG.API_URL+'/api/posts',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+localStorage.getItem('pr_token')},body:JSON.stringify(p)});const data=await r.json();if(!r.ok)throw new Error(data.error||'Could not post');posts.unshift(data)}catch(err){return toast(err.message)}}else{posts.unshift(p);store.set('pr_posts',posts)}e.target.reset();renderPosts();toast('Discussion posted')};$('#clearPosts').onclick=()=>{if(confirm('Reset demo forum posts stored in this browser?')){localStorage.removeItem('pr_posts');location.reload()}};
$('#chatForm').onsubmit=e=>{e.preventDefault();const q=$('#chatInput').value.trim();if(!q)return;$('#chatMessages').insertAdjacentHTML('beforeend',`<div class="bubble user">${esc(q)}</div>`);$('#chatInput').value='';setTimeout(()=>{$('#chatMessages').insertAdjacentHTML('beforeend',`<div class="bubble bot">${esc(aiAnswer(q))}</div>`);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight},180)};$$('[data-prompt]').forEach(b=>b.onclick=()=>{$('#chatInput').value=b.dataset.prompt;$('#chatForm').requestSubmit()});
$('#costCalc').onsubmit=e=>{e.preventDefault();const price=+$('#packPrice').value,count=+$('#packCount').value,g=+$('#gramsEach').value;$('#costOut').textContent=`$${(price/count).toFixed(2)} each • $${(price/(count*g)).toFixed(2)} per gram`};$('#edibleCalc').onsubmit=e=>{e.preventDefault();const total=+$('#totalMg').value,n=+$('#servings').value;$('#edibleOut').textContent=`${(total/n).toFixed(1)} mg per listed serving`};
$('#year').textContent=new Date().getFullYear();renderStrains();renderPosts();renderNews();renderSaved();syncAuth();updateStats();
