(()=>{const API=String(window.PREROLL_CONFIG?.API_URL||"").replace(/\/+$/,"");const $=s=>document.querySelector(s);const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;","\"":"&quot;"}[c]));const fmt=d=>{const x=new Date(d);return Number.isNaN(x.getTime())?"Recent":x.toLocaleString()};let news=[],market=[],posts=[],reviews=[];
async function get(path){const r=await fetch(API+path,{cache:"no-store"});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.error||"Request failed");return d}
const terpAnswers=[
[/terpene/i,"Terpenes are aromatic compounds found in cannabis and many other plants. Common examples include myrcene, limonene, pinene and caryophyllene. A terpene profile can help describe aroma and flavor, but it does not reliably predict how every person will feel."],
[/label|thc|potency/i,"Start with the label: check THC/CBD amounts, serving or package size, batch information, and whether laboratory testing is available. Potency is only one part of evaluating a pre-roll."],
[/indica|sativa|hybrid/i,"Indica, sativa and hybrid are useful shorthand, but they are not precise predictors of effects. For a more useful comparison, look at the cultivar's chemistry, terpene profile and the specific product batch."],
[/pre.?roll|good|quality/i,"For a pre-roll, check the producer, package date, testing information, flower quality, storage condition and whether the label clearly identifies the product. A high THC number alone does not guarantee quality."],
[/myrcene|limonene|pinene|caryophyllene/i,"Those are common cannabis terpenes. Myrcene is often associated with earthy aromas, limonene with citrus, pinene with pine, and caryophyllene with peppery/spicy notes. Aroma descriptions are not promises about effects."]
];
function terpAnswer(q){const hit=terpAnswers.find(([re])=>re.test(q));return hit?hit[1]:"Good question. I can help you understand cannabis terminology, terpenes, strain categories, pre-roll labels and quality factors. Try asking about one of those topics."}
function askTerpenstein(q){const box=$("#terpensteinMessages");if(!box||!q.trim())return;box.insertAdjacentHTML("beforeend","<div class='bubble user'>"+esc(q)+"</div><div class='bubble'><strong>Dr. Terpenstein:</strong><br>"+esc(terpAnswer(q))+"</div>");box.scrollTop=box.scrollHeight}
$("#terpensteinForm")?.addEventListener("submit",e=>{e.preventDefault();const i=$("#terpensteinInput");askTerpenstein(i.value);i.value=""});
document.querySelectorAll("#terpPrompts button").forEach(b=>b.addEventListener("click",()=>askTerpenstein(b.dataset.q)));
function newsRender(){const q=($("#homeSearchInput")?.value||"").toLowerCase();const list=news.filter(n=>!q||JSON.stringify(n).toLowerCase().includes(q)).slice(0,6);$("#newsGrid").innerHTML=list.length?list.map(n=>"<article class='news-card'><span class='source'>"+esc(n.source||"CANNABIS NEWS")+"</span><h3>"+esc(n.title)+"</h3><p>"+esc(n.description||"Latest cannabis coverage.")+"</p><small class='muted'>"+esc(fmt(n.publishedAt))+"</small><p><a class='btn ghost small' href='"+esc(n.url||"#")+"' target='_blank' rel='noopener noreferrer'>Read source ↗</a></p></article>").join(""):"<p class='muted'>No matching live stories.</p>"}
function marketRender(){const q=($("#marketSearch")?.value||"").toLowerCase();const rows=market.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).slice(0,12);$("#marketGrid").innerHTML=rows.length?rows.map(x=>{const name=x.entity_name||x.business_name||x.dba||x.licensee_name||"Licensed business",addr=x.address||x.location_address||x.street_address||"",city=x.city||x.location_city||"",county=x.county||x.location_county||"",type=x.license_type||x.license_category||x.type||"",status=x.license_status||x.status||x.current_status||"";return "<article class='news-card'><span class='source'>NY OCM / OPEN DATA</span><h3>"+esc(name)+"</h3><p>"+esc([addr,city,county].filter(Boolean).join(", "))+"</p><small class='muted'>"+esc([type,status].filter(Boolean).join(" • "))+"</small></article>"}).join(""):"<p class='muted'>No matching records.</p>"}
function communityRender(){$("#forumFeed").innerHTML=posts.slice(0,6).map(p=>"<article class='post'><div class='forum-meta'><span class='pill'>"+esc(p.category)+"</span><span class='pill'>@"+esc(p.author)+"</span></div><h4>"+esc(p.title)+"</h4><p>"+esc(p.body)+"</p><div class='post-actions'><span>▲ "+(p.likes||0)+"</span><span>"+esc(fmt(p.created))+"</span></div></article>").join("")||"<p class='muted'>No discussions yet.</p>";$("#reviewFeed").innerHTML=reviews.slice(0,6).map(r=>"<article class='post'><div class='forum-meta'><span class='pill'>"+esc(r.strain)+"</span><span class='pill'>"+esc(r.author)+"</span></div><h4>"+esc(r.overall)+"/5 overall</h4><p>"+esc(r.text)+"</p><small class='muted'>Burn "+esc(r.burn)+"/5 · Flavor "+esc(r.flavor)+"/5 · Value "+esc(r.value)+" · "+esc(fmt(r.created))+"</small></article>").join("")||"<p class='muted'>No reviews yet.</p>"}
async function loadNews(){const d=await get("/api/news?latest=18");news=d.articles||[];newsRender();$("#newsCount").textContent=news.length}
async function loadMarket(){const d=await get("/api/ny/licenses");market=d.licenses||[];$("#marketCount").textContent=d.activeCount??"—";$("#retailCount").textContent=d.adultUseRetailCount??"—";$("#marketUpdated").textContent="Updated "+fmt(d.fetchedAt);$("#marketStatus").textContent=market.length.toLocaleString()+" records returned • "+(d.activeCount??0)+" active • "+(d.adultUseRetailCount??0)+" adult-use retail";marketRender()}
async function loadCommunity(){const [p,r]=await Promise.all([get("/api/posts"),get("/api/reviews")]);posts=p||[];reviews=r||[];$("#postCount").textContent=posts.length;$("#reviewCount").textContent=reviews.length;communityRender()}
async function loadAll(){const stamp=$("#lastUpdated");stamp.textContent="Refreshing live data…";const results=await Promise.allSettled([loadNews(),loadMarket(),loadCommunity()]);const failed=results.filter(x=>x.status==="rejected").length;stamp.textContent=(failed?"Some live feeds are unavailable":"All live feeds connected")+" • checked "+new Date().toLocaleTimeString()}
$("#homeSearch")?.addEventListener("submit",e=>{e.preventDefault();newsRender();$("#news")?.scrollIntoView({behavior:"smooth"})});$("#homeSearchInput")?.addEventListener("input",newsRender);$("#marketSearch")?.addEventListener("input",marketRender);$("#marketRefresh")?.addEventListener("click",loadMarket);$("#refreshAll")?.addEventListener("click",loadAll);$("#menuBtn")?.addEventListener("click",()=>$("#nav")?.classList.toggle("open"));document.querySelectorAll("#nav a").forEach(a=>a.addEventListener("click",()=>$("#nav")?.classList.remove("open")));$("#year").textContent=new Date().getFullYear();loadAll();setInterval(loadAll,10*60*1000)})();