const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),fs=require('fs'),path=require('path');
const app=express(),PORT=process.env.PORT||3000,SECRET=process.env.JWT_SECRET||'CHANGE-ME-IN-PRODUCTION',DB=process.env.DB_FILE||path.join(__dirname,'db.json');
app.use(cors({origin:process.env.ALLOWED_ORIGIN||'*'}));app.use(express.json({limit:'200kb'}));
function load(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return{users:[],posts:[],reviews:[]}}}function save(db){fs.writeFileSync(DB,JSON.stringify(db,null,2))}function token(user){return jwt.sign({id:user.id,username:user.username,email:user.email},SECRET,{expiresIn:'7d'})}function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');try{req.user=jwt.verify(t,SECRET);next()}catch{return res.status(401).json({error:'Login required'})}}
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.post('/api/signup',async(req,res)=>{const{username,email,password}=req.body||{};if(!username||!email||!password||password.length<6)return res.status(400).json({error:'Username, email and 6+ character password required'});const db=load();if(db.users.some(u=>u.email.toLowerCase()===email.toLowerCase()))return res.status(409).json({error:'Email already registered'});const user={id:Date.now().toString(),username:username.slice(0,24),email:email.toLowerCase(),password:await bcrypt.hash(password,11),created:Date.now()};db.users.push(user);save(db);res.json({token:token(user),user:{id:user.id,username:user.username,email:user.email}})});
app.post('/api/login',async(req,res)=>{const{email,password}=req.body||{},db=load(),user=db.users.find(u=>u.email===String(email).toLowerCase());if(!user||!await bcrypt.compare(password,user.password))return res.status(401).json({error:'Invalid email or password'});res.json({token:token(user),user:{id:user.id,username:user.username,email:user.email}})});
app.get('/api/posts',(req,res)=>res.json(load().posts.sort((a,b)=>b.created-a.created)));
app.post('/api/posts',auth,(req,res)=>{const db=load(),p={id:Date.now(),title:String(req.body.title||'').slice(0,90),category:String(req.body.category||'General').slice(0,40),body:String(req.body.body||'').slice(0,1000),author:req.user.username,likes:0,created:Date.now()};if(!p.title||!p.body)return res.status(400).json({error:'Title and body required'});db.posts.unshift(p);save(db);res.json(p)});
app.post('/api/posts/:id/like',(req,res)=>{const db=load(),p=db.posts.find(x=>String(x.id)===req.params.id);if(!p)return res.status(404).json({error:'Not found'});p.likes=(p.likes||0)+1;save(db);res.json(p)});
app.get('/api/reviews',(req,res)=>res.json(load().reviews));
app.post('/api/reviews',auth,(req,res)=>{const db=load(),r={id:Date.now(),strain:String(req.body.strain||'').slice(0,80),author:req.user.username,text:String(req.body.text||'').slice(0,600),overall:+req.body.overall||0,burn:+req.body.burn||0,flavor:+req.body.flavor||0,value:+req.body.value||0,created:Date.now()};if(!r.strain||!r.text)return res.status(400).json({error:'Strain and review text required'});db.reviews.unshift(r);save(db);res.json(r)});
app.listen(PORT,()=>console.log('Preroll.org API listening on '+PORT));
